Update yahcli tag to `0.1.7`, fix `defaultNodeAccount` (#2486)
* Update yahcli tag in README

Signed-off-by: tinker-michaelj <michael.tinker@hedera.com>

* Add step to check for CI test failures

Signed-off-by: tinker-michaelj <michael.tinker@hedera.com>

* Intentionally break TokenTransactSpecs.nestedHtsCaseStudy() to check config.yml change

Signed-off-by: tinker-michaelj <michael.tinker@hedera.com>

* Revert intentional test failure

Signed-off-by: tinker-michaelj <michael.tinker@hedera.com>

* Try different CI failure test

Signed-off-by: tinker-michaelj <michael.tinker@hedera.com>

* Repeat intentional test failure

Signed-off-by: tinker-michaelj <michael.tinker@hedera.com>

* And finally revert intentional test failure

Signed-off-by: tinker-michaelj <michael.tinker@hedera.com>

* Remove pointless echo

Signed-off-by: tinker-michaelj <michael.tinker@hedera.com>

* Fix support for defaultNodeAccount

Signed-off-by: tinker-michaelj <michael.tinker@hedera.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1551,3 +1551,16 @@ jobs:
           result_path: << parameters.result_path >>
       - store_artifacts:
           path: /results.tar.gz
+      - run:
+          name: Check for CI test failures
+          command: |
+            set -x;
+            set +e;
+            cd /swirlds-platform/regression
+            CI_RESULTS_LOG=$(find results/4N_1C -name hapi-client-combined.log)
+            grep $CI_RESULTS_LOG -e 'status=ERROR' -e 'status=FAILED'
+            if [ "$?" -eq "0" ]; then
+              exit 1
+            else
+              exit 0
+            fi
