Add step to check for CI test failures
Signed-off-by: tinker-michaelj <michael.tinker@hedera.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1551,3 +1551,13 @@ jobs:
           result_path: << parameters.result_path >>
       - store_artifacts:
           path: /results.tar.gz
+      - run:
+          name: Check for CI test failures
+          command: |
+            CI_RESULTS_LOG=$(find . -name hapi-client-combined.log)
+            grep $CI_RESULTS -e 'status=ERROR' -e 'status=FAILED'
+            if [ "$?" -eq "0" ]; then
+              exit 1
+            else
+              exit 0
+            fi
