Add the fail fast logic
Signed-off-by: Nathan Klick <nathan@swirldslabs.com>

diff --git a/.github/workflows/comp-build-release-artifact.yaml b/.github/workflows/comp-build-release-artifact.yaml
--- a/.github/workflows/comp-build-release-artifact.yaml
+++ b/.github/workflows/comp-build-release-artifact.yaml
@@ -295,9 +295,39 @@ jobs:
 
       - name: Display Jenkins Payload
         env:
-          JSON_RESPONSE: ${{ steps.jenkins-integration.outputs.response }}
+          JSON_RESPONSE: ${{ steps.jenkins-integration.outputs.response || steps.jenkins-preview.outputs.response }}
         if: ${{ inputs.trigger-env-deploy == 'integration' || inputs.trigger-env-deploy == 'preview' }}
-        run: jq '.' <<<"${JSON_RESPONSE}"
+        run: |
+          jq '.' <<<"${JSON_RESPONSE}"
+          printf "## Jenkins Response Payload\n\`\`\`json\n%s\n\`\`\`\n" "$(jq '.' <<<"${JSON_RESPONSE}")" >>"${GITHUB_STEP_SUMMARY}"
 
-#      - name: Check for Jenkins Failures
-#        run: |
+      - name: Check for Jenkins Failures (Integration)
+        if: ${{ inputs.trigger-env-deploy == 'integration' }}
+        env:
+          JSON_RESPONSE: ${{ steps.jenkins-integration.outputs.response }}
+        run: |
+          INTEGRATION_TRIGGERED="$(jq '.jobs."build-upgrade-integration".triggered' <<"${JSON_RESPONSE}")"
+          DOCKER_TRIGGERED="$(jq '.jobs."build-upgrade-integration-docker".triggered' <<"${JSON_RESPONSE}")"
+
+          if [[ "${INTEGRATION_TRIGGERED}" != true ]]; then
+            echo "::error title=Jenkins Trigger Failure::Failed to trigger the 'build-upgrade-integration' job via the Jenkins 'integration' pipeline!"
+            exit 1
+          fi
+          
+          if [[ "${DOCKER_TRIGGERED}" != true ]]; then
+            echo "::error title=Jenkins Trigger Failure::Failed to trigger the 'build-upgrade-integration-docker' job via the Jenkins 'integration' pipeline!"
+            exit 1
+          fi
+
+      - name: Check for Jenkins Failures (Preview)
+        if: ${{ inputs.trigger-env-deploy == 'preview' }}
+        env:
+          JSON_RESPONSE: ${{ steps.jenkins-preview.outputs.response }}
+        run: |
+          PREVIEW_TRIGGERED="$(jq '.jobs."build-preview-testnet".triggered' <<"${JSON_RESPONSE}")"
+         
+          if [[ "${PREVIEW_TRIGGERED}" != true ]]; then
+            echo "::error title=Jenkins Trigger Failure::Failed to trigger the 'build-preview-testnet' job via the Jenkins 'preview' pipeline!"
+            exit 1
+          fi
+          
