chore: Added checks for assignee and milestone on PRs and associated issues (#13629)
Signed-off-by: Roger Barker <roger.barker@swirldslabs.com>

diff --git a/.github/workflows/flow-pull-request-formatting.yaml b/.github/workflows/flow-pull-request-formatting.yaml
--- a/.github/workflows/flow-pull-request-formatting.yaml
+++ b/.github/workflows/flow-pull-request-formatting.yaml
@@ -38,6 +38,37 @@ jobs:
     runs-on: [self-hosted, Linux, medium, ephemeral]
     steps:
       - name: Check PR Title
-        uses: aslafy-z/conventional-pr-title-action@a0b851005a0f82ac983a56ead5a8111c0d8e044a # v3.2.0
+        uses: step-security/conventional-pr-title-action@0eae74515f5a79f8773fa04142dd746df76666ac # v1.0.0
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  milestone-check:
+    name: Milestone Check
+    runs-on: [self-hosted, Linux, medium, ephemeral]
+    steps:
+      - name: Check Milestone
+        run: |
+          if [ "${{ github.event.pull_request_target.milestone }}" == "null" ] || [ "${{ github.event.pull_request_target.milestone }}" == "" ]; then
+            echo "Milestone is not set. Failing the workflow."
+            exit 1
+          fi
+
+      - name: Milestone is set
+        run: |
+          echo "Milestone is set."
+
+  assignee-check:
+    name: Assignee Check
+    runs-on: [ self-hosted, Linux, medium, ephemeral ]
+
+    steps:
+      - name: Check Assignee
+        run: |
+          if [ "${{ github.event.pull_request_target.assignee }}" == "null" ] || [ "${{ github.event.pull_request_target.assignee }}" == "" ]; then
+            echo "Assignee is not set. Failing the workflow."
+            exit 1
+          fi
+
+      - name: Assignee is set
+        run: |
+          echo "Assignee is set."
