chore: refactor existing release pipeline
Signed-off-by: Nathan Klick <nathan@swirldslabs.com>

diff --git a/.github/workflows/node-zxc-build-release-artifact.yaml b/.github/workflows/node-zxc-build-release-artifact.yaml
--- a/.github/workflows/node-zxc-build-release-artifact.yaml
+++ b/.github/workflows/node-zxc-build-release-artifact.yaml
@@ -76,10 +76,16 @@ permissions:
   contents: read
 
 jobs:
-  Artifact:
+  validate:
     name: ${{ inputs.custom-job-label || 'Artifact' }}
-    runs-on: [self-hosted, Linux, large, ephemeral]
+    runs-on: [ self-hosted, Linux, large, ephemeral ]
     outputs:
+      branch-name: ${{ steps.parameters.outputs.branch-name }}
+      branch-name-lower: ${{ steps.parameters.outputs.branch-name-lower }}
+      branch-name-safe: ${{ steps.parameters.outputs.branch-name-safe }}
+      commit-prefix: ${{ steps.parameters.outputs.commit-prefix }}
+      commit-id: ${{ steps.parameters.outputs.commit-id }}
+      commit-id-short: ${{ steps.parameters.outputs.commit-id-short }}
       version: ${{ steps.effective-version.outputs.number }}
     steps:
       - name: Install Semantic Version Tools
@@ -94,6 +100,84 @@ jobs:
           semver --version
           echo "::endgroup::"
 
+      - name: Verify Workflow Parameters
+        id: parameters
+        run: |
+          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
+          BRANCH_NAME="${BRANCH_NAME##origin/}"
+          BRANCH_NAME_LOWER="$(echo "${BRANCH_NAME}" | tr '[:upper:]' '[:lower:]')"
+          BRANCH_NAME_SAFE="$(echo "${BRANCH_NAME_LOWER}" | tr '/' '-' | tr '_' '.')"
+
+          COMMIT_PREFIX="adhoc"
+          [[ "${{ inputs.version-policy }}" == "branch-commit" ]] && COMMIT_PREFIX="${BRANCH_NAME_SAFE}"
+
+          echo "branch-name=${BRANCH_NAME}" >>"${GITHUB_OUTPUT}"
+          echo "branch-name-lower=${BRANCH_NAME_LOWER}" >>"${GITHUB_OUTPUT}"
+          echo "branch-name-safe=${BRANCH_NAME_SAFE}" >>"${GITHUB_OUTPUT}"
+          echo "commit-prefix=${COMMIT_PREFIX}" >>"${GITHUB_OUTPUT}"
+          echo "commit-id=${{ github.sha }}" >>"${GITHUB_OUTPUT}"
+          echo "commit-id-short=$(echo "${{ github.sha }}" | cut -c1-8)" >>"${GITHUB_OUTPUT}"
+
+      - name: Verify Version Update (As Specified)
+        if: ${{ inputs.version-policy == 'specified' && !cancelled() && !failure() }}
+        run: |
+          VALID_VERSION="$(semver validate "${{ inputs.new-version }}")"
+
+          if [[ "${VALID_VERSION}" != "valid" ]]; then
+            echo "::error title=Version Error::The supplied new-version parameter (${{ inputs.new-version }}) is invalid and does not conform to the semantic versioning specifications."
+            exit 2
+          fi
+
+      - name: Checkout Code
+        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
+
+      - name: Setup Java
+        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
+        with:
+          distribution: ${{ inputs.java-distribution }}
+          java-version: ${{ inputs.java-version }}
+
+      - name: Setup Gradle
+        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # v2.8.0
+        with:
+          build-root-directory: hedera-node
+          gradle-version: ${{ inputs.gradle-version }}
+          gradle-home-cache-includes: |
+            caches
+            notifications
+            jdks
+
+      - name: Gradle Update Version (As Specified)
+        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # v2.8.0
+        if: ${{ inputs.version-policy == 'specified' && !cancelled() && !failure() }}
+        with:
+          arguments: versionAsSpecified -PnewVersion=${{ inputs.new-version }} --scan
+
+      - name: Gradle Update Version (Branch Commit)
+        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # v2.8.0
+        if: ${{ inputs.version-policy != 'specified' && !cancelled() && !failure() }}
+        with:
+          arguments: versionAsPrefixedCommit -PcommitPrefix=${{ steps.parameters.outputs.commit-prefix }} --scan
+
+      - name: Compute Final Effective Version
+        id: effective-version
+        run: |
+          EFF_VERSION="$(./gradlew showVersion --quiet | tr -d '[:space:]')"
+          echo "number=${EFF_VERSION}" >>"${GITHUB_OUTPUT}"
+
+      - name: Cache Build Version
+        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+        if: ${{ inputs.dry-run-enabled != true && !cancelled() && !failure() }}
+        with:
+          path: version.txt
+          key: node-build-version-${{ steps.effective-version.outputs.number }}-${{ github.sha }}
+
+  Artifact:
+    name: ${{ inputs.custom-job-label || 'Artifact' }}
+    runs-on: [self-hosted, Linux, large, ephemeral]
+    needs:
+      - validate
+    steps:
       - name: Install Deterministic Zip Tooling
         run: |
           echo "::group::Download Binary"
@@ -134,34 +218,6 @@ jobs:
           jq --version
           echo "::endgroup::"
 
-      - name: Verify Workflow Parameters
-        id: parameters
-        run: |
-          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
-          BRANCH_NAME="${BRANCH_NAME##origin/}"
-          BRANCH_NAME_LOWER="$(echo "${BRANCH_NAME}" | tr '[:upper:]' '[:lower:]')"
-          BRANCH_NAME_SAFE="$(echo "${BRANCH_NAME_LOWER}" | tr '/' '-' | tr '_' '.')"
-
-          COMMIT_PREFIX="adhoc"
-          [[ "${{ inputs.version-policy }}" == "branch-commit" ]] && COMMIT_PREFIX="${BRANCH_NAME_SAFE}"
-
-          echo "branch-name=${BRANCH_NAME}" >>"${GITHUB_OUTPUT}"
-          echo "branch-name-lower=${BRANCH_NAME_LOWER}" >>"${GITHUB_OUTPUT}"
-          echo "branch-name-safe=${BRANCH_NAME_SAFE}" >>"${GITHUB_OUTPUT}"
-          echo "commit-prefix=${COMMIT_PREFIX}" >>"${GITHUB_OUTPUT}"
-          echo "commit-id=${{ github.sha }}" >>"${GITHUB_OUTPUT}"
-          echo "commit-id-short=$(echo "${{ github.sha }}" | cut -c1-8)" >>"${GITHUB_OUTPUT}"
-
-      - name: Verify Version Update (As Specified)
-        if: ${{ inputs.version-policy == 'specified' && !cancelled() && !failure() }}
-        run: |
-          VALID_VERSION="$(semver validate "${{ inputs.new-version }}")"
-
-          if [[ "${VALID_VERSION}" != "valid" ]]; then
-            echo "::error title=Version Error::The supplied new-version parameter (${{ inputs.new-version }}) is invalid and does not conform to the semantic versioning specifications."
-            exit 2
-          fi
-
       - name: Checkout Code
         uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
 
@@ -192,22 +248,19 @@ jobs:
             notifications
             jdks
 
-      - name: Gradle Update Version (As Specified)
-        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # v2.8.0
-        if: ${{ inputs.version-policy == 'specified' && !cancelled() && !failure() }}
+      - name: Restore Build Version
+        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
         with:
-          arguments: versionAsSpecified -PnewVersion=${{ inputs.new-version }} --scan
+          fail-on-cache-miss: true
+          path: version.txt
+          key: node-build-version-${{ needs.validate.outputs.version }}-${{ github.sha }}
 
-      - name: Gradle Update Version (Branch Commit)
-        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # v2.8.0
-        if: ${{ inputs.version-policy != 'specified' && !cancelled() && !failure() }}
+      - name: Cache Build Artifacts
+        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+        if: ${{ inputs.dry-run-enabled != true && !cancelled() && !failure() }}
         with:
-          arguments: versionAsPrefixedCommit -PcommitPrefix=${{ steps.parameters.outputs.commit-prefix }} --scan
-
-      - name: Gradle Version Summary
-        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # v2.8.0
-        with:
-          arguments: githubVersionSummary --scan
+          path: ~/artifact-build
+          key: node-build-artifacts-${{ needs.validate.outputs.version }}-${{ github.sha }}
 
       - name: Gradle Assemble
         id: gradle-build
@@ -215,18 +268,10 @@ jobs:
         with:
           arguments: assemble --scan
 
-      - name: Compute Final Effective Version
-        id: effective-version
-        run: |
-          EFF_VERSION="$(./gradlew showVersion --quiet | tr -d '[:space:]')"
-          echo "number=${EFF_VERSION}" >>"${GITHUB_OUTPUT}"
-
-      - name: Cache Build Artifacts
-        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
-        if: ${{ inputs.dry-run-enabled != true && !cancelled() && !failure() }}
+      - name: Gradle Version Summary
+        uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc # v2.8.0
         with:
-          path: ~/artifact-build
-          key: node-build-artifacts-${{ steps.effective-version.outputs.number }}-${{ github.sha }}
+          arguments: githubVersionSummary --scan
 
       - name: Stage Artifact Build Folder
         id: artifact-staging
@@ -245,8 +290,7 @@ jobs:
       - name: Write Artifact Version Descriptor
         working-directory: ${{ steps.artifact-staging.outputs.folder }}
         run: |
-          printf "VERSION=%s\nCOMMIT=%s\nDATE=%s" "${{ steps.effective-version.outputs.number }}" "${{ steps.parameters.outputs.commit-id-short }}" "$(date -u)" \
-            | tee VERSION
+          printf "VERSION=%s\nCOMMIT=%s\nDATE=%s" "${{ needs.validate.outputs.version }}" "${{ needs.validate.outputs.commit-id-short }}" "$(date -u)" | tee VERSION
 
       - name: Create Artifact Archive
         id: artifact-release
@@ -257,9 +301,9 @@ jobs:
           mkdir -p "${ARTIFACT_BASE_DIR}"
 
           if [[ "${POLICY}" == "branch-commit"  ]]; then
-            ARTIFACT_NAME="build-${{ steps.parameters.outputs.branch-name-lower }}-${{ steps.parameters.outputs.commit-id-short }}"
+            ARTIFACT_NAME="build-${{ needs.validate.outputs.branch-name-lower }}-${{ needs.validate.outputs.commit-id-short }}"
           else
-            ARTIFACT_NAME="build-v${{ steps.effective-version.outputs.number }}"
+            ARTIFACT_NAME="build-v${{ needs.validate.outputs.version }}"
           fi
 
           ARTIFACT_FILE="${ARTIFACT_BASE_DIR}/${ARTIFACT_NAME}.zip"
@@ -321,6 +365,7 @@ jobs:
     name: Local Node Images
     runs-on: [ self-hosted, Linux, large, ephemeral ]
     needs:
+      - validate
       - Artifact
     if: ${{ inputs.dry-run-enabled != true && !cancelled() && !failure() }}
     steps:
@@ -364,7 +409,7 @@ jobs:
         with:
           fail-on-cache-miss: true
           path: ~/artifact-build
-          key: node-build-artifacts-${{ needs.Artifact.outputs.version }}-${{ github.sha }}
+          key: node-build-artifacts-${{ needs.validate.outputs.version }}-${{ github.sha }}
 
       - name: Stage SDK Artifacts
         run: |
@@ -379,7 +424,7 @@ jobs:
           push: true
           platforms: linux/amd64,linux/arm64
           context: hedera-node/infrastructure/docker/containers/local-node/network-node-haveged
-          tags: ${{ steps.set-registry.outputs.docker-tag-base }}/network-node-haveged:${{ needs.Artifact.outputs.version }}
+          tags: ${{ steps.set-registry.outputs.docker-tag-base }}/network-node-haveged:${{ needs.validate.outputs.version }}
 
       - name: Build Base Image
         uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1
@@ -389,7 +434,7 @@ jobs:
           push: true
           platforms: linux/amd64,linux/arm64
           context: hedera-node/infrastructure/docker/containers/local-node/network-node-base
-          tags: ${{ steps.set-registry.outputs.docker-tag-base }}/network-node-base:${{ needs.Artifact.outputs.version }}
+          tags: ${{ steps.set-registry.outputs.docker-tag-base }}/network-node-base:${{ needs.validate.outputs.version }}
 
       - name: Build Network Node Image
         uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1
@@ -402,7 +447,7 @@ jobs:
            IMAGE_TAG=${{ needs.Artifact.outputs.version }}
            IMAGE_PREFIX=${{ steps.set-registry.outputs.docker-tag-base }}/
           context: hedera-node/infrastructure/docker/containers/local-node/main-network-node
-          tags: ${{ steps.set-registry.outputs.docker-tag-base }}/main-network-node:${{ needs.Artifact.outputs.version }}
+          tags: ${{ steps.set-registry.outputs.docker-tag-base }}/main-network-node:${{ needs.validate.outputs.version }}
 
       - name: Render Job Summary
         run: |
@@ -412,19 +457,19 @@ jobs:
           printf "| %s | %s | %s | %s |\n" \
             "${{ steps.set-registry.outputs.docker-tag-base }}/network-node-base" \
             "${{ needs.Artifact.outputs.version }}" \
-            "[GCP Console](https://${{ steps.set-registry.outputs.docker-tag-base }}/network-node-base:${{ needs.Artifact.outputs.version }})" \
+            "[GCP Console](https://${{ steps.set-registry.outputs.docker-tag-base }}/network-node-base:${{ needs.validate.outputs.version }})" \
             "linux/amd64, linux/arm64" >> "${GITHUB_STEP_SUMMARY}"
 
           printf "| %s | %s | %s | %s |\n" \
             "${{ steps.set-registry.outputs.docker-tag-base }}/network-node-haveged" \
             "${{ needs.Artifact.outputs.version }}" \
-            "[GCP Console](https://${{ steps.set-registry.outputs.docker-tag-base }}/network-node-haveged:${{ needs.Artifact.outputs.version }})" \
+            "[GCP Console](https://${{ steps.set-registry.outputs.docker-tag-base }}/network-node-haveged:${{ needs.validate.outputs.version }})" \
             "linux/amd64, linux/arm64" >> "${GITHUB_STEP_SUMMARY}"
 
           printf "| %s | %s | %s | %s |\n" \
             "${{ steps.set-registry.outputs.docker-tag-base }}/main-network-node" \
             "${{ needs.Artifact.outputs.version }}" \
-            "[GCP Console](https://${{ steps.set-registry.outputs.docker-tag-base }}/main-network-node:${{ needs.Artifact.outputs.version }})" \
+            "[GCP Console](https://${{ steps.set-registry.outputs.docker-tag-base }}/main-network-node:${{ needs.validate.outputs.version }})" \
             "linux/amd64, linux/arm64" >> "${GITHUB_STEP_SUMMARY}"
 
           printf "\n\n" >> "${GITHUB_STEP_SUMMARY}"
