ci: CITR Phase 1 - Add workflow for XTS
**Description**:

Adds the workflow file to handle XTS testing

- Moves HAPI Testing (Time Consuming) out of compile-application
- Moves Timing Sensitive Tests out of compile-application
- Adds HAPI Testing (Time Consuming) to XTS workflow
- Adds Timing Sensitive Tests to XTS workflow
- Provisions the top level Time Consuming unit test XTS flow
- Adds Hammer Tests to XTS
- Starts thinking about tagging scheme (in progress/development)

**Related Issue(s):

Fixes: #14570
Relates to #14571
Relates to #14407

Signed-off-by: Roger Barker <roger.barker@swirldslabs.com>

diff --git a/.github/workflows/node-zxc-compile-application-code.yaml b/.github/workflows/node-zxc-compile-application-code.yaml
--- a/.github/workflows/node-zxc-compile-application-code.yaml
+++ b/.github/workflows/node-zxc-compile-application-code.yaml
@@ -167,42 +167,42 @@ jobs:
         with:
           node-version: ${{ inputs.node-version }}
 
-#      - name: Setup Control Groups
-#        run: |
-#          echo "::group::Get System Configuration"
-#            USR_ID="$(id -un)"
-#            GRP_ID="$(id -gn)"
-#            GRADLE_MEM_LIMIT="30064771072"
-#            AGENT_MEM_LIMIT="2147483648"
-#            GRADLE_GROUP_NAME="gradle-${{ github.run_id }}"
-#            AGENT_GROUP_NAME="agent-${{ github.run_id }}"
-#          echo "::endgroup::"
-#
-#          echo "::group::Install Control Group Tools"
-#            if ! command -v cgcreate >/dev/null 2>&1; then
-#              sudo apt-get update
-#              sudo apt-get install -y cgroup-tools
-#            fi
-#          echo "::endgroup::"
-#
-#          echo "::group::Create Control Groups"
-#            sudo cgcreate -g cpu,memory:${GRADLE_GROUP_NAME} -a ${USR_ID}:${GRP_ID} -t ${USR_ID}:${GRP_ID}
-#            sudo cgcreate -g cpu,memory:${AGENT_GROUP_NAME} -a ${USR_ID}:${GRP_ID} -t ${USR_ID}:${GRP_ID}
-#          echo "::endgroup::"
-#
-#          echo "::group::Set Control Group Limits"
-#            cgset -r cpu.shares=768 ${GRADLE_GROUP_NAME}
-#            cgset -r cpu.shares=500 ${AGENT_GROUP_NAME}
-#            cgset -r memory.limit_in_bytes=${GRADLE_MEM_LIMIT} ${GRADLE_GROUP_NAME}
-#            cgset -r memory.limit_in_bytes=${AGENT_MEM_LIMIT} ${AGENT_GROUP_NAME}
-#            cgset -r memory.memsw.limit_in_bytes=${GRADLE_MEM_LIMIT} ${GRADLE_GROUP_NAME}
-#            cgset -r memory.memsw.limit_in_bytes=${AGENT_MEM_LIMIT} ${AGENT_GROUP_NAME}
-#          echo "::endgroup::"
-#
-#          echo "::group::Move Runner Processes to Control Groups"
-#            sudo cgclassify --sticky -g cpu,memory:${AGENT_GROUP_NAME} $(pgrep 'Runner.Listener' | tr '\n' ' ')
-#            sudo cgclassify -g cpu,memory:${AGENT_GROUP_NAME} $(pgrep 'Runner.Worker' | tr '\n' ' ')
-#          echo "::endgroup::"
+      #      - name: Setup Control Groups
+      #        run: |
+      #          echo "::group::Get System Configuration"
+      #            USR_ID="$(id -un)"
+      #            GRP_ID="$(id -gn)"
+      #            GRADLE_MEM_LIMIT="30064771072"
+      #            AGENT_MEM_LIMIT="2147483648"
+      #            GRADLE_GROUP_NAME="gradle-${{ github.run_id }}"
+      #            AGENT_GROUP_NAME="agent-${{ github.run_id }}"
+      #          echo "::endgroup::"
+      #
+      #          echo "::group::Install Control Group Tools"
+      #            if ! command -v cgcreate >/dev/null 2>&1; then
+      #              sudo apt-get update
+      #              sudo apt-get install -y cgroup-tools
+      #            fi
+      #          echo "::endgroup::"
+      #
+      #          echo "::group::Create Control Groups"
+      #            sudo cgcreate -g cpu,memory:${GRADLE_GROUP_NAME} -a ${USR_ID}:${GRP_ID} -t ${USR_ID}:${GRP_ID}
+      #            sudo cgcreate -g cpu,memory:${AGENT_GROUP_NAME} -a ${USR_ID}:${GRP_ID} -t ${USR_ID}:${GRP_ID}
+      #          echo "::endgroup::"
+      #
+      #          echo "::group::Set Control Group Limits"
+      #            cgset -r cpu.shares=768 ${GRADLE_GROUP_NAME}
+      #            cgset -r cpu.shares=500 ${AGENT_GROUP_NAME}
+      #            cgset -r memory.limit_in_bytes=${GRADLE_MEM_LIMIT} ${GRADLE_GROUP_NAME}
+      #            cgset -r memory.limit_in_bytes=${AGENT_MEM_LIMIT} ${AGENT_GROUP_NAME}
+      #            cgset -r memory.memsw.limit_in_bytes=${GRADLE_MEM_LIMIT} ${GRADLE_GROUP_NAME}
+      #            cgset -r memory.memsw.limit_in_bytes=${AGENT_MEM_LIMIT} ${AGENT_GROUP_NAME}
+      #          echo "::endgroup::"
+      #
+      #          echo "::group::Move Runner Processes to Control Groups"
+      #            sudo cgclassify --sticky -g cpu,memory:${AGENT_GROUP_NAME} $(pgrep 'Runner.Listener' | tr '\n' ' ')
+      #            sudo cgclassify -g cpu,memory:${AGENT_GROUP_NAME} $(pgrep 'Runner.Worker' | tr '\n' ' ')
+      #          echo "::endgroup::"
 
       - name: Compile
         id: gradle-build
@@ -221,10 +221,10 @@ jobs:
         if: ${{ inputs.enable-unit-tests && steps.gradle-build.conclusion == 'success' && !cancelled() }}
         run: ${GRADLE_EXEC} :reports:testCodeCoverageReport -x :test-clients:test --continue --scan
 
-      - name: Timing Sensitive Tests
-        id: gradle-timing-sensitive
-        if: ${{ inputs.enable-unit-tests && steps.gradle-build.conclusion == 'success' && !cancelled() }}
-        run: ${GRADLE_EXEC} timingSensitive --continue --scan
+      #      - name: Timing Sensitive Tests
+      #        id: gradle-timing-sensitive
+      #        if: ${{ inputs.enable-unit-tests && steps.gradle-build.conclusion == 'success' && !cancelled() }}
+      #        run: ${GRADLE_EXEC} timingSensitive --continue --scan
 
       - name: Publish Unit Test Report
         uses: EnricoMi/publish-unit-test-result-action@30eadd5010312f995f0d3b3cff7fe2984f69409e # v2.16.1
@@ -380,39 +380,39 @@ jobs:
             hedera-node/test-clients/build/hapi-test/**/output/**
           retention-days: 7
 
-      - name: HAPI Testing (Time Consuming)
-        id: gradle-hapi-time-consuming
-        if: ${{ inputs.enable-hapi-tests-time-consuming && steps.gradle-build.conclusion == 'success' && !cancelled() }}
-        env:
-          LC_ALL: en.UTF-8
-          LANG: en_US.UTF-8
-        run: ${GRADLE_EXEC} hapiTestTimeConsuming --scan
-
-      - name: Publish HAPI Test (Time Consuming) Report
-        uses: EnricoMi/publish-unit-test-result-action@30eadd5010312f995f0d3b3cff7fe2984f69409e # v2.16.1
-        if: ${{ inputs.enable-hapi-tests-time-consuming && steps.gradle-build.conclusion == 'success' && !cancelled() }}
-        with:
-          check_name: 'Node: HAPI Test (Time Consuming) Results'
-          json_thousands_separator: ','
-          junit_files: "**/test-clients/build/test-results/test/TEST-*.xml"
-          comment_mode: errors # only comment if we could not find or parse the JUnit XML files
-
-      - name: Upload HAPI Test (Time Consuming) Report Artifacts
-        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
-        if: ${{ inputs.enable-hapi-tests-time-consuming && steps.gradle-build.conclusion == 'success' && !cancelled() }}
-        with:
-          name: HAPI Test (Time Consuming) Report
-          path: "**/test-clients/build/test-results/test/TEST-*.xml"
-          retention-days: 7
-
-      - name: Upload HAPI Test (Time Consuming) Network Logs
-        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
-        if: ${{ inputs.enable-hapi-tests-time-consuming && inputs.enable-network-log-capture && steps.gradle-hapi-time-consuming.conclusion == 'failure' && !cancelled() }}
-        with:
-          name: HAPI Test (Time Consuming) Network Logs
-          path: |
-            hedera-node/test-clients/build/hapi-test/**/output/**
-          retention-days: 7
+      #      - name: HAPI Testing (Time Consuming)
+      #        id: gradle-hapi-time-consuming
+      #        if: ${{ inputs.enable-hapi-tests-time-consuming && steps.gradle-build.conclusion == 'success' && !cancelled() }}
+      #        env:
+      #          LC_ALL: en.UTF-8
+      #          LANG: en_US.UTF-8
+      #        run: ${GRADLE_EXEC} hapiTestTimeConsuming --scan
+      #
+      #      - name: Publish HAPI Test (Time Consuming) Report
+      #        uses: EnricoMi/publish-unit-test-result-action@30eadd5010312f995f0d3b3cff7fe2984f69409e # v2.16.1
+      #        if: ${{ inputs.enable-hapi-tests-time-consuming && steps.gradle-build.conclusion == 'success' && !cancelled() }}
+      #        with:
+      #          check_name: 'Node: HAPI Test (Time Consuming) Results'
+      #          json_thousands_separator: ','
+      #          junit_files: "**/test-clients/build/test-results/test/TEST-*.xml"
+      #          comment_mode: errors # only comment if we could not find or parse the JUnit XML files
+      #
+      #      - name: Upload HAPI Test (Time Consuming) Report Artifacts
+      #        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
+      #        if: ${{ inputs.enable-hapi-tests-time-consuming && steps.gradle-build.conclusion == 'success' && !cancelled() }}
+      #        with:
+      #          name: HAPI Test (Time Consuming) Report
+      #          path: "**/test-clients/build/test-results/test/TEST-*.xml"
+      #          retention-days: 7
+      #
+      #      - name: Upload HAPI Test (Time Consuming) Network Logs
+      #        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
+      #        if: ${{ inputs.enable-hapi-tests-time-consuming && inputs.enable-network-log-capture && steps.gradle-hapi-time-consuming.conclusion == 'failure' && !cancelled() }}
+      #        with:
+      #          name: HAPI Test (Time Consuming) Network Logs
+      #          path: |
+      #            hedera-node/test-clients/build/hapi-test/**/output/**
+      #          retention-days: 7
 
       - name: HAPI Testing (Restart)
         id: gradle-hapi-restart
