ci(chore): Update zxcron-release-branching.yaml to inline archived flow
**Description**:

The workflow `deploy-hedera-services-release-tag.yaml` has been
archived. Needed to pull in the relavent functionality to enable
publishing.

**Related Issue(s)**:

Fixes #17576

Signed-off-by: Roger Barker <roger.barker@swirldslabs.com>

diff --git a/.github/workflows/node-zxcron-release-branching.yaml b/.github/workflows/node-zxcron-release-branching.yaml
--- a/.github/workflows/node-zxcron-release-branching.yaml
+++ b/.github/workflows/node-zxcron-release-branching.yaml
@@ -225,22 +225,127 @@ jobs:
           ref: ${{ needs.check-branch.outputs.branch-name }}
           fetch-depth: 0
 
-      - name: Prepare Dispatch
-        id: prepare-dispatch
+      - name: Install Semantic Version Tools
         run: |
-          REQ_JSON="$(jq --compact-output --null-input \
-                      --arg ref "${{ needs.check-branch.outputs.branch-name }}" \
-                      --arg tagname "${{ needs.check-branch.outputs.tag-name }}" \
-                      --arg strigger "${{ needs.check-branch.outputs.schedule-trigger }}" \
-                      '{"ref": $ref, "tag": { "name": $tagname }, "schedule": { "trigger": $strigger }}')"
+          echo "::group::Download SemVer Binary"
+          sudo curl -L -o /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
+          echo "::endgroup::"
+          echo "::group::Change SemVer Binary Permissions"
+          sudo chmod -v +x /usr/local/bin/semver
+          echo "::endgroup::"
+          echo "::group::Show SemVer Binary Version Info"
+          semver --version
+          echo "::endgroup::"
 
-          echo "payload=${REQ_JSON}" >>"${GITHUB_OUTPUT}"
-          printf "## Dispatch Payload\n\`\`\`json\n%s\n\`\`\`\n" "$(jq '.' <<<"${REQ_JSON}")" >>"${GITHUB_STEP_SUMMARY}"
-
-      - name: Repository Dispatch
-        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
+      - name: Import GPG key for commit signoff
+        id: gpg_import
+        uses: step-security/ghaction-import-gpg@6c8fe4d0126a59d57c21f87c9ae5dd3451fa3cca # v6.1.0
         with:
-          token: ${{ secrets.GH_ACCESS_TOKEN }}
-          repository: hashgraph/hedera-internal-workflows
-          event-type: hedera-svcs-release-tag
-          client-payload: ${{ steps.prepare-dispatch.outputs.payload }}
+          gpg_private_key: ${{ secrets.PLATFORM_GPG_KEY_CONTENTS }}
+          passphrase: ${{ secrets.PLATFORM_GPG_KEY_PASSPHRASE }}
+          git_user_signingkey: true
+          git_commit_gpgsign: true
+          git_tag_gpgsign: true
+          git_config_global: true
+
+      - name: Calculate Version
+        id: version
+        run: |
+          VALID_VERSION="$(semver validate "${{ needs.check-branch.outputs.tag-name }}" | tr -d '[:space:]')"
+
+          if [[ "${VALID_VERSION}" != "valid" ]]; then
+            echo "::error title=Invalid Version::The supplied tag name (${{ needs.check-branch.outputs.tag-name }}) is not a valid semantic version number."
+            exit 1
+          fi
+
+          REL_PART="$(semver get release "${{ needs.check-branch.outputs.tag-name }}")"
+          PRE_PART="$(semver get prerel "${{ needs.check-branch.outputs.tag-name }}")"
+
+          VERSION="${REL_PART}"
+          [[ -n "${PRE_PART}" ]] && VERSION="${VERSION}-${PRE_PART}"
+
+          echo "number=${VERSION}" >> "${GITHUB_OUTPUT}"
+
+      - name: Update Software Version
+        run: sed -i 's/version=.*$/version=${{ steps.version.outputs.number }}/g' gradle.properties
+
+      - name: Commit Version Changes
+        id: git-commit
+        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
+        with:
+          author_name: ${{ secrets.PLATFORM_GIT_USER_NAME }}
+          author_email: ${{ secrets.PLATFORM_GIT_USER_EMAIL }}
+          commit: --signoff --gpg-sign
+          tag: "v${{ steps.version.outputs.number }} -s -m '[Automated Release] Hedera Node v${{ steps.version.outputs.number }}'"
+          message: "[Automated Release] Hedera Node v${{ steps.version.outputs.number }}"
+
+      - name: Compute Commit Identifier
+        id: commit
+        run: |
+          echo "id=$(echo -n "${{ steps.git-commit.outputs.commit_long_sha }}" | tr -d '[:space:]')" >> "${GITHUB_OUTPUT}"
+          echo "short-id=$(echo -n "${{ steps.git-commit.outputs.commit_long_sha }}" | tr -d '[:space:]' | cut -c1-8)" >> "${GITHUB_OUTPUT}"
+
+      - name: Send Slack Notification
+        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
+        with:
+          webhook: ${{ secrets.SLACK_RELEASE_WEBHOOK }}
+          webhook-type: incoming-webhook
+          payload-templated: 'true'
+          payload: |
+            {
+              "attachments": [
+                  {
+                    "color": "#16bec7",
+                    "blocks": [
+                      {
+                        "type": "header",
+                        "text": {
+                          "type": "plain_text",
+                          "text": ":ideograph_advantage: Hedera Services - Automatic Release Tagging",
+                          "emoji": true
+                        }
+                      },
+                      {
+                        "type": "section",
+                        "fields": [
+                          {
+                            "type": "mrkdwn",
+                            "text": "*Tag Name:*"
+                          },
+                          {
+                            "type": "mrkdwn",
+                            "text": "*Source Branch:*"
+                          },
+                          {
+                            "type": "mrkdwn",
+                            "text": "<${{ github.server_url }}/hashgraph/hedera-services/tree/v${{ steps.version.outputs.number }}|v${{ steps.version.outputs.number }}>"
+                          },
+                          {
+                            "type": "mrkdwn",
+                            "text": "<${{ github.server_url }}/hashgraph/hedera-services/tree/${{ needs.check-branch.outputs.branch-name }}|${{ needs.check-branch.outputs.branch-name }}>"
+                          }
+                        ]
+                      },
+                      {
+                        "type": "section",
+                        "text": {
+                          "type": "mrkdwn",
+                          "text": "*Source Commit*: \n<${{ github.server_url }}/${{ github.repository }}/commit/${{ steps.commit.outputs.id  }}|${{ steps.commit.outputs.short-id }}>"
+                        }
+                      },
+                      {
+                        "type": "divider"
+                      },
+                      {
+                        "type": "context",
+                        "elements": [
+                          {
+                            "type": "mrkdwn",
+                            "text": ":watch: Initiated by scheduled repository event at date & time: `${{ needs.check-branch.outputs.schedule-trigger }} UTC`"
+                          }
+                        ]
+                      }
+                    ]
+                  }
+                ]
+              }
