Save

diff --git a/.github/workflows/perf-test-artifact.yaml b/.github/workflows/perf-test-artifact.yaml
--- a/.github/workflows/perf-test-artifact.yaml
+++ b/.github/workflows/perf-test-artifact.yaml
@@ -124,17 +124,17 @@ jobs:
       version-prefix: ${{ steps.effective-version.outputs.prefix }}
       prerelease: ${{ steps.effective-version.outputs.prerelease }}
     steps:
-      - name: Install Semantic Version Tools
-        run: |
-          echo "::group::Download SemVer Binary"
-          sudo curl -L -o /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
-          echo "::endgroup::"
-          echo "::group::Change SemVer Binary Permissions"
-          sudo chmod -v +x /usr/local/bin/semver
-          echo "::endgroup::"
-          echo "::group::Show SemVer Binary Version Info"
-          semver --version
-          echo "::endgroup::"
+#      - name: Install Semantic Version Tools
+#        run: |
+#          echo "::group::Download SemVer Binary"
+#          sudo curl -L -o /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
+#          echo "::endgroup::"
+#          echo "::group::Change SemVer Binary Permissions"
+#          sudo chmod -v +x /usr/local/bin/semver
+#          echo "::endgroup::"
+#          echo "::group::Show SemVer Binary Version Info"
+#          semver --version
+#          echo "::endgroup::"
 
       - name: Verify Workflow Parameters
         id: parameters
@@ -144,74 +144,74 @@ jobs:
           BRANCH_NAME_LOWER="$(echo "${BRANCH_NAME}" | tr '[:upper:]' '[:lower:]')"
           BRANCH_NAME_SAFE="$(echo "${BRANCH_NAME_LOWER}" | tr '/' '-' | tr '_' '.')"
 
-          COMMIT_PREFIX="adhoc"
-          [[ "${{ inputs.version-policy }}" == "branch-commit" ]] && COMMIT_PREFIX="${BRANCH_NAME_SAFE}"
+#          COMMIT_PREFIX="adhoc"
+#          [[ "${{ inputs.version-policy }}" == "branch-commit" ]] && COMMIT_PREFIX="${BRANCH_NAME_SAFE}"
 
-          echo "branch-name=${BRANCH_NAME}" >>"${GITHUB_OUTPUT}"
+#          echo "branch-name=${BRANCH_NAME}" >>"${GITHUB_OUTPUT}"
           echo "branch-name-lower=${BRANCH_NAME_LOWER}" >>"${GITHUB_OUTPUT}"
-          echo "branch-name-safe=${BRANCH_NAME_SAFE}" >>"${GITHUB_OUTPUT}"
-          echo "commit-prefix=${COMMIT_PREFIX}" >>"${GITHUB_OUTPUT}"
-          echo "commit-id=${{ github.sha }}" >>"${GITHUB_OUTPUT}"
+#          echo "branch-name-safe=${BRANCH_NAME_SAFE}" >>"${GITHUB_OUTPUT}"
+#          echo "commit-prefix=${COMMIT_PREFIX}" >>"${GITHUB_OUTPUT}"
+#          echo "commit-id=${{ github.sha }}" >>"${GITHUB_OUTPUT}"
           echo "commit-id-short=$(echo "${{ github.sha }}" | cut -c1-8)" >>"${GITHUB_OUTPUT}"
 
-      - name: Verify Version Update (As Specified)
-        if: ${{ inputs.version-policy == 'specified' && !cancelled() && !failure() }}
-        run: |
-          VALID_VERSION="$(semver validate "${{ inputs.new-version }}")"
+#      - name: Verify Version Update (As Specified)
+#        if: ${{ inputs.version-policy == 'specified' && !cancelled() && !failure() }}
+#        run: |
+#          VALID_VERSION="$(semver validate "${{ inputs.new-version }}")"
+#
+#          if [[ "${VALID_VERSION}" != "valid" ]]; then
+#            echo "::error title=Version Error::The supplied new-version parameter (${{ inputs.new-version }}) is invalid and does not conform to the semantic versioning specifications."
+#            exit 2
+#          fi
 
-          if [[ "${VALID_VERSION}" != "valid" ]]; then
-            echo "::error title=Version Error::The supplied new-version parameter (${{ inputs.new-version }}) is invalid and does not conform to the semantic versioning specifications."
-            exit 2
-          fi
+#      - name: Checkout Code
+#        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+#
+#      - name: Setup Java
+#        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
+#        with:
+#          distribution: ${{ inputs.java-distribution }}
+#          java-version: ${{ inputs.java-version }}
+#
+#      - name: Setup Gradle
+#        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
+#        with:
+#          gradle-version: ${{ inputs.gradle-version }}
+#
+#      - name: Gradle Update Version (As Specified)
+#        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
+#        if: ${{ inputs.version-policy == 'specified' && !cancelled() && !failure() }}
+#        with:
+#          gradle-version: ${{ inputs.gradle-version }}
+#          arguments: versionAsSpecified -PnewVersion=${{ inputs.new-version }} --scan
+#
+#      - name: Gradle Update Version (Branch Commit)
+#        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
+#        if: ${{ inputs.version-policy != 'specified' && !cancelled() && !failure() }}
+#        with:
+#          gradle-version: ${{ inputs.gradle-version }}
+#          arguments: versionAsPrefixedCommit -PcommitPrefix=${{ steps.parameters.outputs.commit-prefix }} --scan
+#
+#      - name: Compute Final Effective Version
+#        id: effective-version
+#        run: |
+#          EFF_VERSION="$(./gradlew showVersion --quiet | tr -d '[:space:]')"
+#          PRERELEASE_SUFFIX="$(semver get prerel "${EFF_VERSION}")"
+#          PRERELEASE="false"
+#          [[ -n "${PRERELEASE_SUFFIX}" ]] && PRERELEASE="true"
+#
+#          MAJOR_VERSION="$(semver get major "${EFF_VERSION}")"
+#          MINOR_VERSION="$(semver get minor "${EFF_VERSION}")"
+#
+#          echo "number=${EFF_VERSION}" >>"${GITHUB_OUTPUT}"
+#          echo "prefix=${MAJOR_VERSION}.${MINOR_VERSION}" >>"${GITHUB_OUTPUT}"
+#          echo "prerelease=${PRERELEASE}" >>"${GITHUB_OUTPUT}"
 
-      - name: Checkout Code
-        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
-
-      - name: Setup Java
-        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
-        with:
-          distribution: ${{ inputs.java-distribution }}
-          java-version: ${{ inputs.java-version }}
-
-      - name: Setup Gradle
-        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
-        with:
-          gradle-version: ${{ inputs.gradle-version }}
-
-      - name: Gradle Update Version (As Specified)
-        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
-        if: ${{ inputs.version-policy == 'specified' && !cancelled() && !failure() }}
-        with:
-          gradle-version: ${{ inputs.gradle-version }}
-          arguments: versionAsSpecified -PnewVersion=${{ inputs.new-version }} --scan
-
-      - name: Gradle Update Version (Branch Commit)
-        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
-        if: ${{ inputs.version-policy != 'specified' && !cancelled() && !failure() }}
-        with:
-          gradle-version: ${{ inputs.gradle-version }}
-          arguments: versionAsPrefixedCommit -PcommitPrefix=${{ steps.parameters.outputs.commit-prefix }} --scan
-
-      - name: Compute Final Effective Version
-        id: effective-version
-        run: |
-          EFF_VERSION="$(./gradlew showVersion --quiet | tr -d '[:space:]')"
-          PRERELEASE_SUFFIX="$(semver get prerel "${EFF_VERSION}")"
-          PRERELEASE="false"
-          [[ -n "${PRERELEASE_SUFFIX}" ]] && PRERELEASE="true"
-
-          MAJOR_VERSION="$(semver get major "${EFF_VERSION}")"
-          MINOR_VERSION="$(semver get minor "${EFF_VERSION}")"
-
-          echo "number=${EFF_VERSION}" >>"${GITHUB_OUTPUT}"
-          echo "prefix=${MAJOR_VERSION}.${MINOR_VERSION}" >>"${GITHUB_OUTPUT}"
-          echo "prerelease=${PRERELEASE}" >>"${GITHUB_OUTPUT}"
-
-      - name: Cache Build Version
-        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
-        with:
-          path: version.txt
-          key: node-build-version-${{ steps.effective-version.outputs.number }}-${{ github.sha }}
+#      - name: Cache Build Version
+#        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
+#        with:
+#          path: version.txt
+#          key: node-build-version-${{ steps.effective-version.outputs.number }}-${{ github.sha }}
 
   build-artifact:
     name: Build Artifact
@@ -221,46 +221,6 @@ jobs:
     outputs:
       build-version: ${{ steps.artifact-release.outputs.build-version }}
     steps:
-      - name: Install Deterministic Zip Tooling
-        run: |
-          echo "::group::Download Binary"
-          sudo curl -L -o /usr/local/bin/deterministic-zip https://github.com/timo-reymann/deterministic-zip/releases/download/1.2.0/deterministic-zip_linux-amd64
-          echo "::endgroup::"
-          echo "::group::Change Binary Permissions"
-          sudo chmod -v +x /usr/local/bin/deterministic-zip
-          echo "::endgroup::"
-          echo "::group::Show Binary Version Info"
-          deterministic-zip --version
-          echo "::endgroup::"
-
-      - name: Install JSON Tools
-        run: |
-          if ! command -v jq >/dev/null 2>&1; then
-            echo "::group::Setup JQ Command"
-            sudo apt update
-            sudo apt install -y jq
-            echo "::endgroup::"
-          fi
-
-          JQ_VERSION="$(jq --version)"
-          if [[ "${JQ_VERSION}" != "jq-1.6" ]]; then
-            echo "::group::Updating JQ Version"
-            sudo apt update
-            sudo apt upgrade -y jq
-            echo "::endgroup::"
-          fi
-
-          if ! command -v tee >/dev/null 2>&1; then
-            echo "::group::Setup Tee Command"
-            sudo apt update
-            sudo apt install -y coreutils
-            echo "::endgroup::"
-          fi
-
-          echo "::group::Show JQ Version"
-          jq --version
-          echo "::endgroup::"
-
       - name: Checkout Code
         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
 
@@ -273,61 +233,6 @@ jobs:
       - name: Setup Google Cloud SDK
         uses: google-github-actions/setup-gcloud@e30db14379863a8c79331b04a9969f4c1e225e0b # v1.1.1
 
-      - name: Setup Java
-        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
-        with:
-          distribution: ${{ inputs.java-distribution }}
-          java-version: ${{ inputs.java-version }}
-
-      - name: Setup Gradle
-        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
-        with:
-          gradle-version: ${{ inputs.gradle-version }}
-
-      - name: Restore Build Version
-        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
-        with:
-          fail-on-cache-miss: true
-          path: version.txt
-          key: node-build-version-${{ needs.validate.outputs.version }}-${{ github.sha }}
-
-      - name: Cache Build Artifacts
-        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
-        with:
-          path: ~/artifact-build
-          key: node-build-artifacts-${{ needs.validate.outputs.version }}-${{ github.sha }}
-
-      - name: Gradle Assemble
-        id: gradle-build
-        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
-        with:
-          gradle-version: ${{ inputs.gradle-version }}
-          arguments: assemble --scan
-
-      - name: Gradle Version Summary
-        uses: gradle/gradle-build-action@842c587ad8aa4c68eeba24c396e15af4c2e9f30a # v2.9.0
-        with:
-          gradle-version: ${{ inputs.gradle-version }}
-          arguments: githubVersionSummary --scan
-
-      - name: Stage Artifact Build Folder
-        id: artifact-staging
-        run: |
-          BUILD_BASE_DIR="${HOME}/artifact-build"
-          mkdir -p "${BUILD_BASE_DIR}/data/lib"
-          mkdir -p "${BUILD_BASE_DIR}/data/apps"
-
-          cp -f hedera-node/data/lib/*.jar "${BUILD_BASE_DIR}/data/lib"
-          cp -f hedera-node/data/apps/*.jar "${BUILD_BASE_DIR}/data/apps"
-          cp -f hedera-node/configuration/update/immediate.sh "${BUILD_BASE_DIR}"
-          cp -f hedera-node/configuration/update/during-freeze.sh "${BUILD_BASE_DIR}"
-
-          echo "folder=${BUILD_BASE_DIR}" >>"${GITHUB_OUTPUT}"
-
-      - name: Write Artifact Version Descriptor
-        working-directory: ${{ steps.artifact-staging.outputs.folder }}
-        run: |
-          printf "VERSION=%s\nCOMMIT=%s\nDATE=%s" "${{ needs.validate.outputs.version }}" "${{ needs.validate.outputs.commit-id-short }}" "$(date -u)" | tee VERSION
 
       - name: Create Artifact Archive
         id: artifact-release
@@ -337,11 +242,8 @@ jobs:
           ARTIFACT_BASE_DIR="${HOME}/artifact-release"
           mkdir -p "${ARTIFACT_BASE_DIR}"
 
-          if [[ "${POLICY}" == "branch-commit"  ]]; then
-            ARTIFACT_NAME="build-${{ needs.validate.outputs.branch-name-lower }}-${{ needs.validate.outputs.commit-id-short }}"
-          else
-            ARTIFACT_NAME="build-v${{ needs.validate.outputs.version }}"
-          fi
+          ARTIFACT_NAME="build-${{ needs.validate.outputs.branch-name-lower }}-${{ needs.validate.outputs.commit-id-short }}"
+
 
           ARTIFACT_FILE="${ARTIFACT_BASE_DIR}/${ARTIFACT_NAME}.zip"
           deterministic-zip -D -vr "${ARTIFACT_FILE}" *
@@ -351,21 +253,16 @@ jobs:
           echo "name=${ARTIFACT_NAME}" >>"${GITHUB_OUTPUT}"
           echo "file=${ARTIFACT_FILE}" >>"${GITHUB_OUTPUT}"
 
-      - name: Compute SHA Hash
-        working-directory: ${{ steps.artifact-release.outputs.folder }}
-        run: |
-          ARTIFACT_NAME="${{ steps.artifact-release.outputs.name }}"
-          sha384sum "${ARTIFACT_NAME}.zip" | tee "${ARTIFACT_NAME}.sha384"
-
       - name: Check If Release Artifact Exist in Bucket
         id: check-if-exist
         run: |
           set +e
-          ARTIFACT_NAME="${{ steps.artifact-release.outputs.name }}"
+          ARTIFACT_NAME="build-v${{ needs.validate.outputs.version }}"
           ARTIFACT_PATH="gs://${{ secrets.bucket-name }}/${ARTIFACT_NAME}.zip"
           echo "ARTIFACT_PATH=${ARTIFACT_PATH}"
           gsutil -q stat "${ARTIFACT_PATH}"
           PATH_EXIST=$?
+          while loop check
           if [ ${PATH_EXIST} -eq 0 ]; then
             echo "Artifact Already Exist"
             echo "exist=true" >>"${GITHUB_OUTPUT}"
@@ -373,11 +270,3 @@ jobs:
             echo "Artifact Not Exist"
             echo "exist=false" >>"${GITHUB_OUTPUT}"
           fi
-
-      - name: Upload Artifacts (DevOps GCP Bucket)
-        if: ${{ steps.check-if-exist.outputs.exist == 'false' }}
-        uses: google-github-actions/upload-cloud-storage@e95a15f226403ed658d3e65f40205649f342ba2c # v1.0.3
-        with:
-          path: ${{ steps.artifact-release.outputs.folder }}
-          destination: ${{ secrets.bucket-name }}
-          parent: false
