chore: format / fix warning
Signed-off-by: Jendrik Johannes <jendrik.johannes@gmail.com>

diff --git a/.github/workflows/zxc-verify-docker-build-determinism.yaml b/.github/workflows/zxc-verify-docker-build-determinism.yaml
--- a/.github/workflows/zxc-verify-docker-build-determinism.yaml
+++ b/.github/workflows/zxc-verify-docker-build-determinism.yaml
@@ -136,61 +136,61 @@ jobs:
           sudo apt-get update
           sudo apt-get install --yes --no-install-recommends skopeo jq
 
-#      - name: Install KillAll
-#        if: ${{ steps.baseline.outputs.exists == 'false' && !failure() && !cancelled() }}
-#        run: sudo apt-get install --yes --no-install-recommends psmisc
+      #      - name: Install KillAll
+      #        if: ${{ steps.baseline.outputs.exists == 'false' && !failure() && !cancelled() }}
+      #        run: sudo apt-get install --yes --no-install-recommends psmisc
 
-#      - name: Create Docker Working Directory
-#        if: ${{ steps.baseline.outputs.exists == 'false' && !failure() && !cancelled() }}
-#        run: |
-#          USER="$(id -un)"
-#          GROUP="$(id -gn)"
-#          sudo mkdir -p /x
-#          sudo chown -vR ${USER}:${GROUP} /x
-#          sudo ls -lah /x
+      #      - name: Create Docker Working Directory
+      #        if: ${{ steps.baseline.outputs.exists == 'false' && !failure() && !cancelled() }}
+      #        run: |
+      #          USER="$(id -un)"
+      #          GROUP="$(id -gn)"
+      #          sudo mkdir -p /x
+      #          sudo chown -vR ${USER}:${GROUP} /x
+      #          sudo ls -lah /x
 
-#      - name: Remove Docker from Self Hosted Runners
-#        if: ${{ steps.baseline.outputs.exists == 'false' && !failure() && !cancelled() }}
-#        run: |
-#          set -x
-#          sudo killall dockerd || true
-#          sudo killall containerd || true
-#          sudo rm -rvf /usr/bin/*containerd* || true
-#          sudo rm -rvf /usr/bin/docker* || true
-#          sudo rm -rvf /usr/local/bin/docker* || true
-#          sudo rm -rvf /usr/local/bin/*lima* || true
+      #      - name: Remove Docker from Self Hosted Runners
+      #        if: ${{ steps.baseline.outputs.exists == 'false' && !failure() && !cancelled() }}
+      #        run: |
+      #          set -x
+      #          sudo killall dockerd || true
+      #          sudo killall containerd || true
+      #          sudo rm -rvf /usr/bin/*containerd* || true
+      #          sudo rm -rvf /usr/bin/docker* || true
+      #          sudo rm -rvf /usr/local/bin/docker* || true
+      #          sudo rm -rvf /usr/local/bin/*lima* || true
 
-#      - name: Setup Containerd Support
-#        uses: crazy-max/ghaction-setup-containerd@60acbf31e6572da7b83a4ed6b428ed92a35ff4d7 # v3.0.0
-#        if: ${{ steps.baseline.outputs.exists == 'false' && !failure() && !cancelled() }}
-#        with:
-#          containerd-version: v1.7.2
+      #      - name: Setup Containerd Support
+      #        uses: crazy-max/ghaction-setup-containerd@60acbf31e6572da7b83a4ed6b428ed92a35ff4d7 # v3.0.0
+      #        if: ${{ steps.baseline.outputs.exists == 'false' && !failure() && !cancelled() }}
+      #        with:
+      #          containerd-version: v1.7.2
 
-#      - name: Setup Docker Support
-#        uses: step-security/ghaction-setup-docker@42e219a378b907a83f1b323a1458fbf352af3ffd # v3.3.0
-#        if: ${{ steps.baseline.outputs.exists == 'false' && !failure() && !cancelled() }}
-#        env:
-#          HOME: /x
-#        with:
-#          version: v25.0.5
-#          daemon-config: |
-#            {
-#              "registry-mirrors": [
-#                "https://hub.mirror.docker.lat.ope.eng.hashgraph.io"
-#              ]
-#            }
+      #      - name: Setup Docker Support
+      #        uses: step-security/ghaction-setup-docker@42e219a378b907a83f1b323a1458fbf352af3ffd # v3.3.0
+      #        if: ${{ steps.baseline.outputs.exists == 'false' && !failure() && !cancelled() }}
+      #        env:
+      #          HOME: /x
+      #        with:
+      #          version: v25.0.5
+      #          daemon-config: |
+      #            {
+      #              "registry-mirrors": [
+      #                "https://hub.mirror.docker.lat.ope.eng.hashgraph.io"
+      #              ]
+      #            }
 
-#      - name: Configure Default Docker Context
-#        if: ${{ steps.baseline.outputs.exists == 'false' && !failure() && !cancelled() }}
-#        run: |
-#          set -x
-#          if grep setup-docker-action < <(docker context ls --format '{{ .Name }}') >/dev/null; then
-#            docker context rm -f setup-docker-action
-#          fi
-#
-#          DOCKER_CONTEXT_PATH="$(sudo find /x -name docker.sock | tr -d '[:space:]')"
-#          docker context create setup-docker-action --docker "host=unix://${DOCKER_CONTEXT_PATH}"
-#          docker context use setup-docker-action
+      #      - name: Configure Default Docker Context
+      #        if: ${{ steps.baseline.outputs.exists == 'false' && !failure() && !cancelled() }}
+      #        run: |
+      #          set -x
+      #          if grep setup-docker-action < <(docker context ls --format '{{ .Name }}') >/dev/null; then
+      #            docker context rm -f setup-docker-action
+      #          fi
+      #
+      #          DOCKER_CONTEXT_PATH="$(sudo find /x -name docker.sock | tr -d '[:space:]')"
+      #          docker context create setup-docker-action --docker "host=unix://${DOCKER_CONTEXT_PATH}"
+      #          docker context use setup-docker-action
 
       - name: Setup QEmu Support
         uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3.3.0
@@ -326,9 +326,9 @@ jobs:
             sudo apt-get install --yes --no-install-recommends skopeo
           fi
 
-#      - name: Install KillAll (Linux)
-#        if: ${{ runner.os == 'Linux' }}
-#        run: sudo apt-get install --yes --no-install-recommends psmisc
+      #      - name: Install KillAll (Linux)
+      #        if: ${{ runner.os == 'Linux' }}
+      #        run: sudo apt-get install --yes --no-install-recommends psmisc
 
       - name: Install Skopeo and JQ (macOS)
         if: ${{ runner.os == 'macOS' }}
@@ -360,14 +360,14 @@ jobs:
           tar -xzf "${{ needs.generate-baseline.outputs.name }}"
           mv "sdk" "${{ github.workspace }}/${{ env.DOCKER_CONTEXT_PATH }}/"
 
-#      - name: Create Docker Working Directory
-#        if: ${{ runner.os == 'Linux' }}
-#        run: |
-#          USER="$(id -un)"
-#          GROUP="$(id -gn)"
-#          sudo mkdir -p /x
-#          sudo chown -vR ${USER}:${GROUP} /x
-#          sudo ls -lah /x
+      #      - name: Create Docker Working Directory
+      #        if: ${{ runner.os == 'Linux' }}
+      #        run: |
+      #          USER="$(id -un)"
+      #          GROUP="$(id -gn)"
+      #          sudo mkdir -p /x
+      #          sudo chown -vR ${USER}:${GROUP} /x
+      #          sudo ls -lah /x
 
       - name: Remove Preinstalled Docker
         if: ${{ runner.os == 'macOS' }}
@@ -390,37 +390,37 @@ jobs:
         id: home
         run: echo "directory=$(tr -d '[:space:]' < <(cd ~ && pwd))" >> "${GITHUB_OUTPUT}"
 
-#      - name: Setup Containerd Support
-#        uses: crazy-max/ghaction-setup-containerd@60acbf31e6572da7b83a4ed6b428ed92a35ff4d7 # v3.0.0
-#        if: ${{ runner.os == 'Linux' }}
-#        with:
-#          containerd-version: v1.7.2
-#
-#      - name: Setup Docker Support
-#        uses: step-security/ghaction-setup-docker@42e219a378b907a83f1b323a1458fbf352af3ffd # v3.3.0
-#        env:
-#          HOME: ${{ runner.os == 'Linux' && '/x' || steps.home.outputs.directory }}
-#        with:
-#          version: v25.0.5
-#          daemon-config: |
-#            {
-#              "registry-mirrors": [
-#                "https://hub.mirror.docker.lat.ope.eng.hashgraph.io"
-#              ]
-#            }
-#
-#      - name: Configure Default Docker Context
-#        env:
-#          SEARCH_PATH: ${{ runner.os == 'Linux' && '/x' || steps.home.outputs.directory }}
-#        run: |
-#          set -x
-#          if grep setup-docker-action < <(docker context ls --format '{{ .Name }}') >/dev/null; then
-#            docker context rm -f setup-docker-action
-#          fi
-#
-#          DOCKER_CONTEXT_PATH="$(sudo find "${SEARCH_PATH}" -name docker.sock | tr -d '[:space:]')"
-#          docker context create setup-docker-action --docker "host=unix://${DOCKER_CONTEXT_PATH}"
-#          docker context use setup-docker-action
+      #      - name: Setup Containerd Support
+      #        uses: crazy-max/ghaction-setup-containerd@60acbf31e6572da7b83a4ed6b428ed92a35ff4d7 # v3.0.0
+      #        if: ${{ runner.os == 'Linux' }}
+      #        with:
+      #          containerd-version: v1.7.2
+      #
+      #      - name: Setup Docker Support
+      #        uses: step-security/ghaction-setup-docker@42e219a378b907a83f1b323a1458fbf352af3ffd # v3.3.0
+      #        env:
+      #          HOME: ${{ runner.os == 'Linux' && '/x' || steps.home.outputs.directory }}
+      #        with:
+      #          version: v25.0.5
+      #          daemon-config: |
+      #            {
+      #              "registry-mirrors": [
+      #                "https://hub.mirror.docker.lat.ope.eng.hashgraph.io"
+      #              ]
+      #            }
+      #
+      #      - name: Configure Default Docker Context
+      #        env:
+      #          SEARCH_PATH: ${{ runner.os == 'Linux' && '/x' || steps.home.outputs.directory }}
+      #        run: |
+      #          set -x
+      #          if grep setup-docker-action < <(docker context ls --format '{{ .Name }}') >/dev/null; then
+      #            docker context rm -f setup-docker-action
+      #          fi
+      #
+      #          DOCKER_CONTEXT_PATH="$(sudo find "${SEARCH_PATH}" -name docker.sock | tr -d '[:space:]')"
+      #          docker context create setup-docker-action --docker "host=unix://${DOCKER_CONTEXT_PATH}"
+      #          docker context use setup-docker-action
 
       - name: Setup QEmu Support
         uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v3.3.0
